#!/bin/bash
set -e

mariadb -u root -p"$MYSQL_ROOT_PASSWORD" <<EOSQL
  CREATE DATABASE IF NOT EXISTS \`${AUTH_DB}\`;
  CREATE USER IF NOT EXISTS '${AUTH_USER}'@'%' IDENTIFIED BY '${AUTH_PASS}';
  GRANT ALL PRIVILEGES ON \`${AUTH_DB}\`.* TO '${AUTH_USER}'@'%';

  CREATE DATABASE IF NOT EXISTS \`${IP_MANAGEMENT_DB}\`;
  CREATE USER IF NOT EXISTS '${IP_MANAGEMENT_USER}'@'%' IDENTIFIED BY '${IP_MANAGEMENT_PASS}';
  GRANT ALL PRIVILEGES ON \`${IP_MANAGEMENT_DB}\`.* TO '${IP_MANAGEMENT_USER}'@'%';

  FLUSH PRIVILEGES;
EOSQL
